In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("static/covidDataStuffs.csv")

In [3]:
print(df)

     Jurisdiction of Occurrence Week Ending Date  All Cause  Natural Cause  \
0                       Alabama           1/4/20       1082           1009
1                       Alabama          1/11/20       1127           1060
2                       Alabama          1/18/20       1039            976
3                       Alabama          1/25/20       1056            982
4                       Alabama           2/1/20       1026            949
...                         ...              ...        ...            ...
8419                    Wyoming           1/7/23         99             91
8420                    Wyoming          1/14/23        106            102
8421                    Wyoming          1/21/23         79             78
8422                    Wyoming          1/28/23         87             87
8423                    Wyoming           2/4/23         59             59

      COVID-19 (U071, Multiple Cause of Death)  \
0                                          0.0
1                                          0.0
2                                          0.0
3                                          NaN
4                                          0.0
...                                        ...
8419                                       NaN
8420                                       NaN
8421                                       NaN
8422                                       NaN
8423                                       NaN

      COVID-19 (U071, Underlying Cause of Death)
0                                            0.0
1                                            0.0
2                                            0.0
3                                            0.0
4                                            0.0
...                                          ...
8419                                         NaN
8420                                         NaN
8421                                         NaN
8422                                         NaN
8423                                         NaN

[8424 rows x 6 columns]

In [8]:
headers = df.columns.to_list()
print(headers)

['Jurisdiction of Occurrence', 'Week Ending Date', 'All Cause', 'Natural Cause', 'COVID-19 (U071, Multiple Cause of Death)', 'COVID-19 (U071, Underlying Cause of Death)']

In [9]:
# Aggregate data by months for each state
df_months = df['Week Ending Date' == '1/4/20']

KeyError: False

In [10]:
# df['Week Ending Date' == 1/4/20] # Really get to understand why this isn't working... Ugh
df[df['Week Ending Date'] == '1/4/20']

,Jurisdiction of Occurrence,Week Ending Date,All Cause,Natural Cause,"COVID-19 (U071, Multiple Cause of Death)","COVID-19 (U071, Underlying Cause of Death)"
0,Alabama,1/4/20,1082,1009,0.0,0.0
162,Alaska,1/4/20,89,71,0.0,0.0
324,Arizona,1/4/20,1301,1182,0.0,0.0
486,Arkansas,1/4/20,672,630,0.0,0.0
648,California,1/4/20,5888,5437,0.0,0.0
810,Colorado,1/4/20,854,758,0.0,0.0
972,Connecticut,1/4/20,633,574,0.0,0.0
1134,Delaware,1/4/20,199,179,0.0,0.0
1296,District of Columbia,1/4/20,132,109,0.0,0.0
1458,Florida,1/4/20,4341,3928,0.0,0.0
1620,Georgia,1/4/20,1803,1657,0.0,0.0
1782,Hawaii,1/4/20,242,222,0.0,0.0
1944,Idaho,1/4/20,278,255,0.0,0.0
2106,Illinois,1/4/20,2191,2007,0.0,0.0
2268,Indiana,1/4/20,1470,1357,0.0,0.0
2430,Iowa,1/4/20,665,618,0.0,0.0
2592,Kansas,1/4/20,591,542,0.0,0.0
2754,Kentucky,1/4/20,1093,1001,0.0,0.0
2916,Louisiana,1/4/20,927,837,0.0,0.0
3078,Maine,1/4/20,320,289,0.0,0.0
3240,Maryland,1/4/20,1049,937,0.0,0.0
3402,Massachusetts,1/4/20,1242,1131,0.0,0.0
3564,Michigan,1/4/20,2015,1863,0.0,0.0
3726,Minnesota,1/4/20,1009,929,0.0,0.0
3888,Mississippi,1/4/20,673,600,0.0,0.0
4050,Missouri,1/4/20,1327,1203,0.0,0.0
4212,Montana,1/4/20,231,205,0.0,0.0
4374,Nebraska,1/4/20,346,322,0.0,0.0
4536,Nevada,1/4/20,521,465,0.0,0.0
4698,New Hampshire,1/4/20,261,240,0.0,0.0
4860,New Jersey,1/4/20,1628,1480,0.0,0.0
5022,New Mexico,1/4/20,408,358,0.0,0.0
5184,New York,1/4/20,2164,2019,0.0,0.0
5346,New York City,1/4/20,1155,1067,0.0,0.0
5508,North Carolina,1/4/20,2003,1835,0.0,0.0
5670,North Dakota,1/4/20,149,139,0.0,0.0
5832,Ohio,1/4/20,2541,2328,0.0,0.0
5994,Oklahoma,1/4/20,901,821,0.0,0.0
6156,Oregon,1/4/20,737,683,0.0,0.0
6318,Pennsylvania,1/4/20,2785,2572,0.0,0.0
6480,Rhode Island,1/4/20,225,205,0.0,0.0
6642,South Carolina,1/4/20,1085,994,0.0,0.0
6804,South Dakota,1/4/20,170,145,0.0,0.0
6966,Tennessee,1/4/20,1614,1451,0.0,0.0
7128,Texas,1/4/20,4325,3949,0.0,0.0
7290,Utah,1/4/20,392,350,0.0,0.0
7452,Vermont,1/4/20,92,87,0.0,0.0
7614,Virginia,1/4/20,1438,1314,0.0,0.0
7776,Washington,1/4/20,1183,1069,0.0,0.0
7938,West Virginia,1/4/20,474,439,0.0,0.0
8100,Wisconsin,1/4/20,1118,1017,0.0,0.0
8262,Wyoming,1/4/20,144,130,0.0,0.0

In [11]:
print(headers)

['Jurisdiction of Occurrence', 'Week Ending Date', 'All Cause', 'Natural Cause', 'COVID-19 (U071, Multiple Cause of Death)', 'COVID-19 (U071, Underlying Cause of Death)']

In [12]:
df['All Cause' == 1082]

KeyError: False

In [13]:
df['Week Ending Date']

0        1/4/20
1       1/11/20
2       1/18/20
3       1/25/20
4        2/1/20
         ...
8419     1/7/23
8420    1/14/23
8421    1/21/23
8422    1/28/23
8423     2/4/23
Name: Week Ending Date, Length: 8424, dtype: object

In [14]:
days = [x for x in range(1,13)]

In [15]:
years = [x for x in range(2020,2024)]

In [16]:
df['Week Ending Date'] = pd.to_datetime(df['Week Ending Date'])  # Convert 'Date' column to datetime type

In [17]:
df['COVID-19 (U071, Underlying Cause of Death)']
df['Jurisdiction of Occurrence']

0       Alabama
1       Alabama
2       Alabama
3       Alabama
4       Alabama
         ...
8419    Wyoming
8420    Wyoming
8421    Wyoming
8422    Wyoming
8423    Wyoming
Name: Jurisdiction of Occurrence, Length: 8424, dtype: object

In [18]:
df.groupby([df['Week Ending Date'].dt.year, df['Week Ending Date'].dt.month])['Jurisdiction of Occurrence'].sum()

Week Ending Date  Week Ending Date
2020              1                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  2                   AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  3                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  4                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  5                   AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  6                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  7                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  8                   AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  9                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  10                  AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  11                  AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  12                  AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
2021              1                   AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  2                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  3                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  4                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  5                   AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  6                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  7                   AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  8                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  9                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  10                  AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  11                  AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  12                  AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
2022              1                   AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  2                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  3                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  4                   AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  5                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  6                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  7                   AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  8                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  9                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  10                  AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
                  11                  AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  12                  AlabamaAlabamaAlabamaAlabamaAlabamaAlaskaAlask...
2023              1                   AlabamaAlabamaAlabamaAlabamaAlaskaAlaskaAlaska...
                  2                   AlabamaAlaskaArizonaArkansasCaliforniaColorado...
Name: Jurisdiction of Occurrence, dtype: object

In [19]:
df['Week Ending Date'].dt.year

0       2020
1       2020
2       2020
3       2020
4       2020
        ...
8419    2023
8420    2023
8421    2023
8422    2023
8423    2023
Name: Week Ending Date, Length: 8424, dtype: int64

In [20]:
df['Week Ending Date'].dt.month

0       1
1       1
2       1
3       1
4       2
       ..
8419    1
8420    1
8421    1
8422    1
8423    2
Name: Week Ending Date, Length: 8424, dtype: int64

In [21]:
df['Week Ending Date'].dt.day

0        4
1       11
2       18
3       25
4        1
        ..
8419     7
8420    14
8421    21
8422    28
8423     4
Name: Week Ending Date, Length: 8424, dtype: int64

In [22]:
import pandas as pd

# assuming your data is in a DataFrame called 'df'

# convert 'Week Ending Date' column to datetime type
df['Week Ending Date'] = pd.to_datetime(df['Week Ending Date'])

# set the 'Week Ending Date' column as the index
df.set_index('Week Ending Date', inplace=True)

# group the data by state and resample by month
df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()

# reset the index to make 'Jurisdiction of Occurrence' and 'Week Ending Date' columns
df_monthly = df_monthly.reset_index()

/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
/var/folders/w6/b4rt07vs4d3fp4pw6gqqn3ph0000gn/T/ipykernel_8578/1376796034.py:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()

In [ ]:
df

# Now lets showcase the monthly COVID data each in its own CSV

In [25]:
state_month_combinations = df_monthly[['Jurisdiction of Occurrence', 'Week Ending Date']].drop_duplicates()

In [26]:
state_month_combinations

     Jurisdiction of Occurrence Week Ending Date
0                       Alabama       2020-01-31
1                       Alabama       2020-02-29
2                       Alabama       2020-03-31
3                       Alabama       2020-04-30
4                       Alabama       2020-05-31
...                         ...              ...
1971                    Wyoming       2022-10-31
1972                    Wyoming       2022-11-30
1973                    Wyoming       2022-12-31
1974                    Wyoming       2023-01-31
1975                    Wyoming       2023-02-28

[1976 rows x 2 columns]

In [27]:
# assuming you already have the 'df_monthly' DataFrame from the previous example

# get unique combinations of state and month
state_month_combinations = df_monthly[['Jurisdiction of Occurrence', 'Week Ending Date']].drop_duplicates()

# iterate over the combinations and save each subset of data into a separate .csv file
for state, month in state_month_combinations.itertuples(index=False):
    subset = df_monthly[(df_monthly['Jurisdiction of Occurrence'] == state) & (df_monthly['Week Ending Date'].dt.month == month.month) & (df_monthly['Week Ending Date'].dt.year == month.year)]
    filename = f"{state}_{month.strftime('%Y-%m')}.csv"
    subset.to_csv(filename, index=False)

In [29]:
state_month_combinations

     Jurisdiction of Occurrence Week Ending Date
0                       Alabama       2020-01-31
1                       Alabama       2020-02-29
2                       Alabama       2020-03-31
3                       Alabama       2020-04-30
4                       Alabama       2020-05-31
...                         ...              ...
1971                    Wyoming       2022-10-31
1972                    Wyoming       2022-11-30
1973                    Wyoming       2022-12-31
1974                    Wyoming       2023-01-31
1975                    Wyoming       2023-02-28

[1976 rows x 2 columns]

In [24]:
state_month_combinations = df_monthly[['Jurisdiction of Occurrence', 'Week Ending Date']].drop_duplicates()

for state, month in state_month_combinations.itertuples(index=False):
    subset = df_monthly[(df_monthly['Jurisdiction of Occurrence'] == state) & (df_monthly['Week Ending Date'].dt.month == month.month) & (df_monthly['Week Ending Date'].dt.year == month.year)]
    filename = f"./static/month/{state}_{month.strftime('%Y-%m')}.csv"
    subset.to_csv(filename, index=False)

OSError: Cannot save file into a non-existent directory: 'static/month'

### Explore Different Static Folder Structure

In [32]:
import os

In [46]:
os.chdir('/Users/kollintrujillo/PycharmProjects/flaskProject')

In [47]:
os.getcwd()

'/Users/kollintrujillo/PycharmProjects/flaskProject'

In [48]:
state_month_combinations = df_monthly[['Jurisdiction of Occurrence', 'Week Ending Date']].drop_duplicates()

for state, month in state_month_combinations.itertuples(index=False):
    subset = df_monthly[(df_monthly['Jurisdiction of Occurrence'] == state) & (df_monthly['Week Ending Date'].dt.month == month.month) & (df_monthly['Week Ending Date'].dt.year == month.year)]
    filename = f"./static/state/{state}/{month.strftime('%Y-%m')}.csv"
    subset.to_csv(filename, index=False)

In [43]:
# states = []
# for keys in state_month_combinations['Jurisdiction of Occurrence']:
#     print(keys)
#     states.append(keys)
# states = sorted(set(states))

In [ ]:
# states

In [40]:
os.chdir('/Users/kollintrujillo/PycharmProjects/flaskProject/static/state/')

In [41]:
os.getcwd()

'/Users/kollintrujillo/PycharmProjects/flaskProject/static/state'

In [44]:
# import os
# for state in states:
#     # Directory
#     directory = f"{state}"

#     # Parent Directory path
#     parent_dir = "./"
#     path = os.path.join(parent_dir, directory)

#     # Create the directory
#     # 'GeeksForGeeks' in
#     # '/home / User / Documents'
#     os.mkdir(path)
#     print("Directory '% s' created" % directory)

## Explore All Data

In [49]:
os.chdir('/Users/kollintrujillo/PycharmProjects/flaskProject')

In [50]:
os.getcwd()

'/Users/kollintrujillo/PycharmProjects/flaskProject'

In [51]:
state_month_combinations = df_monthly[['Jurisdiction of Occurrence', 'Week Ending Date']].drop_duplicates()

In [52]:
test = df_monthly[['Jurisdiction of Occurrence', 'Week Ending Date']].drop_duplicates()

In [53]:
test

     Jurisdiction of Occurrence Week Ending Date
0                       Alabama       2020-01-31
1                       Alabama       2020-02-29
2                       Alabama       2020-03-31
3                       Alabama       2020-04-30
4                       Alabama       2020-05-31
...                         ...              ...
1971                    Wyoming       2022-10-31
1972                    Wyoming       2022-11-30
1973                    Wyoming       2022-12-31
1974                    Wyoming       2023-01-31
1975                    Wyoming       2023-02-28

[1976 rows x 2 columns]

In [54]:
for state, month in state_month_combinations.itertuples(index=False):
    print(month[6])

TypeError: 'Timestamp' object is not subscriptable

# Save allData

In [66]:
state_month_combinations = df_monthly[['Jurisdiction of Occurrence', 'Week Ending Date']].drop_duplicates()

for state, month in state_month_combinations.itertuples(index=False):
    subset = df_monthly[(df_monthly['Week Ending Date'].dt.month == month.month) & (df_monthly['Week Ending Date'].dt.year == month.year)]
    filename = f"./static/allData/{pd.to_datetime(month).date()}.csv"
    subset.to_csv(filename, index=False)

# FIX STRUCTURE TO REMOVE DAY OF THE MONTH WITH THIS... JUST LIKE YEAR-MONTH OR MONTH-YEAR?

# Back

In [58]:
df_monthly

,Jurisdiction of Occurrence,Week Ending Date,All Cause,Natural Cause,"COVID-19 (U071, Multiple Cause of Death)","COVID-19 (U071, Underlying Cause of Death)"
0,Alabama,2020-01-31,4304,4027,0.0,0.0
1,Alabama,2020-02-29,5503,5108,0.0,0.0
2,Alabama,2020-03-31,4280,3941,23.0,20.0
3,Alabama,2020-04-30,4579,4223,304.0,285.0
4,Alabama,2020-05-31,5728,5235,478.0,446.0
...,...,...,...,...,...,...
1971,Wyoming,2022-10-31,448,398,0.0,0.0
1972,Wyoming,2022-11-30,451,404,11.0,0.0
1973,Wyoming,2022-12-31,518,476,0.0,0.0
1974,Wyoming,2023-01-31,371,358,0.0,0.0
1975,Wyoming,2023-02-28,59,59,0.0,0.0

In [74]:
# for state, month in state_month_combinations.itertuples(index=False):
#     subset = df_monthly[(df_monthly['Week Ending Date'].dt.month == month.month) & (df_monthly['Week Ending Date'].dt.year == month.year)]
#     print(subset)

In [75]:
subset

,Jurisdiction of Occurrence,Week Ending Date,All Cause,Natural Cause,"COVID-19 (U071, Multiple Cause of Death)","COVID-19 (U071, Underlying Cause of Death)"
37,Alabama,2023-02-28,651,651,27.0,21.0
75,Alaska,2023-02-28,29,29,0.0,0.0
113,Arizona,2023-02-28,1079,1079,28.0,15.0
151,Arkansas,2023-02-28,537,537,23.0,14.0
189,California,2023-02-28,3466,3466,103.0,66.0
227,Colorado,2023-02-28,602,602,18.0,0.0
265,Connecticut,2023-02-28,384,384,30.0,20.0
303,Delaware,2023-02-28,21,21,0.0,0.0
341,District of Columbia,2023-02-28,52,52,0.0,0.0
379,Florida,2023-02-28,3405,3405,152.0,102.0
417,Georgia,2023-02-28,986,986,37.0,26.0
455,Hawaii,2023-02-28,193,193,0.0,0.0
493,Idaho,2023-02-28,237,237,0.0,0.0
531,Illinois,2023-02-28,1867,1867,60.0,43.0
569,Indiana,2023-02-28,739,739,25.0,18.0
607,Iowa,2023-02-28,434,434,21.0,14.0
645,Kansas,2023-02-28,446,446,10.0,0.0
683,Kentucky,2023-02-28,491,491,37.0,24.0
721,Louisiana,2023-02-28,59,59,0.0,0.0
759,Maine,2023-02-28,293,293,17.0,0.0
797,Maryland,2023-02-28,804,804,52.0,29.0
835,Massachusetts,2023-02-28,974,974,57.0,37.0
873,Michigan,2023-02-28,1553,1553,57.0,34.0
911,Minnesota,2023-02-28,654,654,28.0,16.0
949,Mississippi,2023-02-28,495,495,24.0,13.0
987,Missouri,2023-02-28,840,840,26.0,17.0
1025,Montana,2023-02-28,23,23,0.0,0.0
1063,Nebraska,2023-02-28,50,50,0.0,0.0
1101,Nevada,2023-02-28,379,379,10.0,0.0
1139,New Hampshire,2023-02-28,213,213,11.0,0.0
1177,New Jersey,2023-02-28,1246,1246,58.0,40.0
1215,New Mexico,2023-02-28,164,164,0.0,0.0
1253,New York,2023-02-28,1850,1850,101.0,61.0
1291,New York City,2023-02-28,960,960,54.0,39.0
1329,North Carolina,2023-02-28,1559,1559,81.0,48.0
1367,North Dakota,2023-02-28,113,113,0.0,0.0
1405,Ohio,2023-02-28,1236,1236,51.0,28.0
1443,Oklahoma,2023-02-28,457,457,19.0,11.0
1481,Oregon,2023-02-28,435,435,10.0,0.0
1519,Pennsylvania,2023-02-28,2248,2248,121.0,83.0
1557,Rhode Island,2023-02-28,179,179,0.0,0.0
1595,South Carolina,2023-02-28,931,931,49.0,30.0
1633,South Dakota,2023-02-28,0,0,0.0,0.0
1671,Tennessee,2023-02-28,1088,1088,66.0,41.0
1709,Texas,2023-02-28,2597,2597,109.0,75.0
1747,Utah,2023-02-28,363,363,0.0,0.0
1785,Vermont,2023-02-28,97,97,0.0,0.0
1823,Virginia,2023-02-28,1159,1159,76.0,47.0
1861,Washington,2023-02-28,922,922,31.0,17.0
1899,West Virginia,2023-02-28,445,445,30.0,19.0
1937,Wisconsin,2023-02-28,833,833,31.0,22.0
1975,Wyoming,2023-02-28,59,59,0.0,0.0

In [ ]:
# for state, month in state_month_combinations.itertuples(index=False):
#     print(pd.to_datetime(month).date())

In [ ]:
print(state)

In [65]:
# for state, month in state_month_combinations.itertuples(index=False):
#     print(pd.to_datetime(month).date())

### Back to main

In [ ]:
df_monthly['Week Ending Date'].month == month.month

In [ ]:
df['Week Ending Date'] = pd.to_datetime(df['Week Ending Date'])

In [ ]:
df['Week Ending Date'] = pd.to_datetime(df['Week Ending Date'])

In [ ]:
df

In [ ]:
df['Week Ending Date'] = pd.to_datetime(df['Week Ending Date'])

In [ ]:
df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()

In [ ]:
import pandas as pd

# create a sample DataFrame with a MultiIndex
df = pd.DataFrame({'A': [1, 2, 3, 4],
                   'B': [5, 6, 7, 8]},
                  index=pd.MultiIndex.from_tuples([('x', 1), ('x', 2), ('y', 1), ('y', 2)], names=['X', 'Y']))
print(df)

In [ ]:
# reset the index
df_reset = df.reset_index()
print(df_reset)

In [ ]:
import pandas as pd

# assuming your data is in a DataFrame called 'df'

# convert 'Week Ending Date' column to datetime type
df['Week Ending Date'] = pd.to_datetime(df['Week Ending Date'])

# set the 'Week Ending Date' column as the index
df.set_index('Week Ending Date', inplace=True)

# group the data by state and resample by month
df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()

# reset the index to make 'Jurisdiction of Occurrence' and 'Week Ending Date' columns
df_monthly = df_monthly.reset_index()

In [ ]:
df

In [ ]:
df['Week Ending Date'] = pd.to_datetime(df['Week Ending Date'])
df

In [ ]:
df.set_index('Week Ending Date', inplace=True)
df

In [ ]:
# group the data by state and resample by month
df_monthly = df.groupby('Jurisdiction of Occurrence').resample('M').sum()
df_monthly

In [ ]:
df_monthly = df_monthly.reset_index()
df_monthly

In [ ]:
show = pd.read_csv(f"./static/month/Alabama_2020-10.csv")
show['COVID-19 (U071, Underlying Cause of Death)'][0]

In [ ]:
df[df['Week Ending Date' == '1/31/20']]

# Experiment

In [ ]:
state_month_combinations[(state_month_combinations["Week Ending Date"].dt.month == 1) & (state_month_combinations["Week Ending Date"].dt.year== 2021)]

In [79]:
for state in states:
    print(f'<option value="{state}">{state}</option>')

<option value="Alabama">Alabama</option>
<option value="Alaska">Alaska</option>
<option value="Arizona">Arizona</option>
<option value="Arkansas">Arkansas</option>
<option value="California">California</option>
<option value="Colorado">Colorado</option>
<option value="Connecticut">Connecticut</option>
<option value="Delaware">Delaware</option>
<option value="District of Columbia">District of Columbia</option>
<option value="Florida">Florida</option>
<option value="Georgia">Georgia</option>
<option value="Hawaii">Hawaii</option>
<option value="Idaho">Idaho</option>
<option value="Illinois">Illinois</option>
<option value="Indiana">Indiana</option>
<option value="Iowa">Iowa</option>
<option value="Kansas">Kansas</option>
<option value="Kentucky">Kentucky</option>
<option value="Louisiana">Louisiana</option>
<option value="Maine">Maine</option>
<option value="Maryland">Maryland</option>
<option value="Massachusetts">Massachusetts</option>
<option value="Michigan">Michigan</option>
<option value="Minnesota">Minnesota</option>
<option value="Mississippi">Mississippi</option>
<option value="Missouri">Missouri</option>
<option value="Montana">Montana</option>
<option value="Nebraska">Nebraska</option>
<option value="Nevada">Nevada</option>
<option value="New Hampshire">New Hampshire</option>
<option value="New Jersey">New Jersey</option>
<option value="New Mexico">New Mexico</option>
<option value="New York">New York</option>
<option value="New York City">New York City</option>
<option value="North Carolina">North Carolina</option>
<option value="North Dakota">North Dakota</option>
<option value="Ohio">Ohio</option>
<option value="Oklahoma">Oklahoma</option>
<option value="Oregon">Oregon</option>
<option value="Pennsylvania">Pennsylvania</option>
<option value="Rhode Island">Rhode Island</option>
<option value="South Carolina">South Carolina</option>
<option value="South Dakota">South Dakota</option>
<option value="Tennessee">Tennessee</option>
<option value="Texas">Texas</option>
<option value="Utah">Utah</option>
<option value="Vermont">Vermont</option>
<option value="Virginia">Virginia</option>
<option value="Washington">Washington</option>
<option value="West Virginia">West Virginia</option>
<option value="Wisconsin">Wisconsin</option>
<option value="Wyoming">Wyoming</option>

In [82]:
months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
for month in months:
    print(f'<option value="{month}">{month}</option>')

<option value="January">January</option>
<option value="February">February</option>
<option value="March">March</option>
<option value="April">April</option>
<option value="May">May</option>
<option value="June">June</option>
<option value="July">July</option>
<option value="August">August</option>
<option value="September">September</option>
<option value="October">October</option>
<option value="November">November</option>
<option value="December">December</option>

In [88]:
states

['Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'New York City',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming']

    <form action="/action_page.php">
        <label for="fname">First name:</label><br>
        <input type="text" id="fname" name="fname" value="John"><br>
        <label for="lname">Last name:</label><br>
        <input type="text" id="lname" name="lname" value="Doe"><br><br>
        <input type="submit" value="Submit">
      </form>
      

    <label for="month">Choose a month:</label>
    <select name="months" id="month">
      <option value="January">January</option>
      <option value="February">February</option>
      <option value="March">March</option>
      <option value="April">April</option>
      <option value="May">May</option>
      <option value="June">June</option>
      <option value="July">July</option>
      <option value="August">August</option>
      <option value="September">September</option>
      <option value="October">October</option>
      <option value="November">November</option>
      <option value="December">December</option>
    </select>

    <label for="state">Choose a year:</label>
    <select name="states" id="state">
      <option value="Alabama">Alabama</option>
      <option value="Alaska">Alaska</option>
      <option value="Arizona">Arizona</option>
      <option value="Arkansas">Arkansas</option>
      <option value="California">California</option>
      <option value="Colorado">Colorado</option>
      <option value="Connecticut">Connecticut</option>
      <option value="Delaware">Delaware</option>
      <option value="District of Columbia">District of Columbia</option>
      <option value="Florida">Florida</option>
      <option value="Georgia">Georgia</option>
      <option value="Hawaii">Hawaii</option>
      <option value="Idaho">Idaho</option>
      <option value="Illinois">Illinois</option>
      <option value="Indiana">Indiana</option>
      <option value="Iowa">Iowa</option>
      <option value="Kansas">Kansas</option>
      <option value="Kentucky">Kentucky</option>
      <option value="Louisiana">Louisiana</option>
      <option value="Maine">Maine</option>
      <option value="Maryland">Maryland</option>
      <option value="Massachusetts">Massachusetts</option>
      <option value="Michigan">Michigan</option>
      <option value="Minnesota">Minnesota</option>
      <option value="Mississippi">Mississippi</option>
      <option value="Missouri">Missouri</option>
      <option value="Montana">Montana</option>
      <option value="Nebraska">Nebraska</option>
      <option value="Nevada">Nevada</option>
      <option value="New Hampshire">New Hampshire</option>
      <option value="New Jersey">New Jersey</option>
      <option value="New Mexico">New Mexico</option>
      <option value="New York">New York</option>
      <option value="New York City">New York City</option>
      <option value="North Carolina">North Carolina</option>
      <option value="North Dakota">North Dakota</option>
      <option value="Ohio">Ohio</option>
      <option value="Oklahoma">Oklahoma</option>
      <option value="Oregon">Oregon</option>
      <option value="Pennsylvania">Pennsylvania</option>
      <option value="Rhode Island">Rhode Island</option>
      <option value="South Carolina">South Carolina</option>
      <option value="South Dakota">South Dakota</option>
      <option value="Tennessee">Tennessee</option>
      <option value="Texas">Texas</option>
      <option value="Utah">Utah</option>
      <option value="Vermont">Vermont</option>
      <option value="Virginia">Virginia</option>
      <option value="Washington">Washington</option>
      <option value="West Virginia">West Virginia</option>
      <option value="Wisconsin">Wisconsin</option>
      <option value="Wyoming">Wyoming</option>
    </select>

In [87]:
for state in states:
    print(f"{state}")

Alabama,
Alaska,
Arizona,
Arkansas,
California,
Colorado,
Connecticut,
Delaware,
District of Columbia,
Florida,
Georgia,
Hawaii,
Idaho,
Illinois,
Indiana,
Iowa,
Kansas,
Kentucky,
Louisiana,
Maine,
Maryland,
Massachusetts,
Michigan,
Minnesota,
Mississippi,
Missouri,
Montana,
Nebraska,
Nevada,
New Hampshire,
New Jersey,
New Mexico,
New York,
New York City,
North Carolina,
North Dakota,
Ohio,
Oklahoma,
Oregon,
Pennsylvania,
Rhode Island,
South Carolina,
South Dakota,
Tennessee,
Texas,
Utah,
Vermont,
Virginia,
Washington,
West Virginia,
Wisconsin,
Wyoming,

In [89]:
testSt = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'New York City', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']

In [90]:
len(testSt)

52

In [91]:
years = [x for x in range(2020,2023)]

In [93]:
years = [x for x in range(2020,2024)]

In [94]:
years

[2020, 2021, 2022, 2023]

In [98]:
def inclusive_range(start, end):
    return range(start, end + 1)

In [99]:
years = [x for x in inclusive_range(2020, 2023)]

In [100]:
years

[2020, 2021, 2022, 2023]

In [103]:
years = [year for year in inclusive_range(2020, 2023)]

In [104]:
years

[2020, 2021, 2022, 2023]